// frontend/React/src/components/CreateTodo.jsx
import React from 'react'
import { useTodoStore } from '../store/useTodoStore'
import { PlusCircle } from 'lucide-react';

const CreateTodo = () => {
  const { createTask } = useTodoStore();

  return (
    <div className="w-3/4">
      <form className="flex flex-col gap-2" onSubmit={(e) => {
        e.preventDefault();
        const task = e.target.task.value;
        const done = false;
        createTask(task, done);
        e.target.reset();
      }}>
        <div className="relative">
          <input type="text" name="task" placeholder="Nowe zadanie" className="border-2 rounded-lg p-2 w-full pr-9" required />
          <button type="submit" className="text-green-600 rounded-lg p-1 absolute top-1/2 right-1 -translate-y-1/2 cursor-pointer"><PlusCircle className="size-6"/></button>
        </div>
      </form>
    </div>
  )
}

export default CreateTodo

// frontend/Svelte/todo-app/src/lib/components/CreateTodo.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { CirclePlus } from "lucide-svelte";
  import type { Todo } from "$lib/types/todo";
  export let todos: Todo[];

  const dispatch = createEventDispatcher<{ add: Todo }>();
  let newTask = "";

  async function add() {
    if (!newTask.trim()) return;
    const res = await fetch("/api/todos", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ task: newTask }),
    });
    if (res.ok) {
      const todo: Todo = await res.json();
      dispatch("add", todo);
      todos = [...todos, todo];
      newTask = "";
    }
  }
</script>

<form on:submit|preventDefault={add} class="flex space-x-2 mb-4 w-3/4 relative">
  <input
    bind:value={newTask}
    placeholder="Nowe zadanie"
    class="border-2 rounded-lg p-2 w-full pr-9"
  />
  <button type="submit" class="absolute top-1/2 -translate-y-1/2 right-4">
    <CirclePlus class="text-green-600 size-6 cursor-pointer" />
  </button>
</form>
